# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20181109_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='suggestion',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
