# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_image_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='suggestion',
        ),
    ]
